import "~/src/styles/globals.css";
import { inter } from "~/src/styles/font";
import { ThemeProvider } from "~/src/components/theme-provider";
import NavBar from "~/src/components/navbar/navbar";
import { Toaster } from "~/src/components/ui/toaster";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/favicon.jpg"
          type="image/jpg"
          sizes="32px"
        />
      </head>
      <body className={`font-sans ${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar className="px-4" />
          <main className="h-[calc(100vh-3rem)] p-4">{children}</main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
