# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD backend /app

# Install Poetry
RUN pip install poetry

# Install backend dependencies
RUN poetry install

# Make port 4000 available to the world outside this container
EXPOSE 4000

# Run the command to start the server
CMD ["poetry", "run", "python", "backend/main.py"]