@startuml add_video
participant Client
participant Course
participant CourseMaterialVideo

Client -> Course: add_videos(video: CourseMaterialVideo)
activate Course

alt video is instance of CourseMaterialVideo
    Course -> Course: self.__videos.append(video)
    Course --> Client: True
else
    Course --> Client: False
end

deactivate Course
@enduml
