@startuml

actor User
participant "UI" as Server
participant Controller


User -> Server: authenticate_user(username, password)
Server -> Controller: authenticate_user(username, password)
activate Controller
alt User authentication successful
    Controller --> Server: user_object
    Server --> User: user_object
else User authentication failed
    Controller --> Server: 401 Unauthorized
    Server --> User: 401 Unauthorized
end

@enduml