@startuml

actor User
participant Controller
participant Cart
participant "User" as UserClass

User -> Controller: get_Course_in_cart(UserClass)
activate Controller

alt User is authenticated
    Controller -> UserClass: UserClass.get_cart()
    activate UserClass
    UserClass --> Controller: obj_cart
    deactivate UserClass

    alt Cart is not empty
        loop for each Course in obj_cart.get_Courses()
            Controller -> Course: Course.get_id()
            activate Course
            Course --> Controller: Course_id
            deactivate Course

            Controller -> Course: Course.get_name(), Course.get_description(), Course.get_price(), Course.get_average_rating(), Course.get_banner_image_url()
            activate Course
            Course --> Controller: name, description, price, rating, banner_image
            deactivate Course

        end
    else Cart is empty
        Controller --> User: []
    end

else User is not authenticated
    Controller --> User: []
end

@enduml