@startuml Remove Course From Cart
actor "User" as UserActor

participant "UI" as Server
participant Controller
participant "User" as UserClass
participant Cart


UserActor -> Server: Remove Course
Server -> Controller: remove_course_from_cart(current_user, course_id_query)
activate Controller
Controller -> UserClass: search_course_by_id(course_id_query)
activate UserClass
UserClass --> Controller: return_course
deactivate UserClass
Controller -> UserClass: get_cart()
activate UserClass
UserClass --> Controller: return_cart
deactivate UserClass
Controller -> Cart: remove_course(course)
activate Cart
Cart --> Controller: Course removed from cart
deactivate Cart
Controller --> Server: return_cart
deactivate Controller

Server -> UserActor : return_cart