@startuml Get Cart

actor "User" as UserActor

participant "UI" as Server
participant Controller
participant "User" as UserClass
participant Cart


UserActor -> Server: Get Course In Cart
Server -> Controller: get_course_in_cart(current_user)
activate Controller
Controller -> UserClass: get_cart()
activate UserClass
UserClass --> Controller: return_cart
deactivate UserClass
Controller -> Cart: get_courses()
activate Cart
Cart --> Controller: return List of courses in cart
deactivate Cart
Controller --> Server: return_cart
deactivate Controller

Server --> UserActor: return_cart

@enduml