@startuml

actor User
participant Controller
participant Cart
participant Course
participant "User" as UserClass

User -> Controller: remove_course_to_cart(UserClass, course_id)
activate Controller


Controller -> Controller: search_course_by_id(course_uuid)

Controller -> UserClass: UserClass.get_cart()
activate UserClass
UserClass --> Controller: Cart
deactivate UserClass

alt Course is in the cart
    Controller -> Cart: Cart.get_courses()
    activate Cart
    Cart --> Controller: courses_list
    deactivate Cart

    Controller -> Course: Course in courses_list
    activate Course
    Course --> Controller: is_in_cart
    deactivate Course

    alt Course is in the cart
        Controller -> Cart: Cart.remove_course(Course)
        activate Cart
        Cart --> Controller: course_removed
        deactivate Cart

        Controller --> User: "Succeed"
    else Course is not in the cart
        Controller --> User: "Fail"
    end
else Course not found
    Controller --> User: "Fail"

end

@enduml