@startuml Category
actor User

participant "UI" as Server
participant Controller
participant Category

User -> Server: Get All Category
activate Server

Server -> Controller: get_all_categories()
activate Controller
Controller --> Server: List of categories
deactivate Controller

' Server --> User: return category 

' User -> Server: Get All Category
Server -> Controller: get_category_by_id(category_id)
activate Controller
Controller -> Category: search_category_by_id(category_id)
activate Category
Category --> Controller: category
deactivate Category
Controller --> Server: CategoryInfo
deactivate Controller

Server --> User: return category 

@enduml