@startuml Udemy Sequence Diagram (Quiz Operations)

actor "User" as UserActor
participant "UI" as Server
participant Controller
participant Course
participant "User" as UserClass

UserActor -> Server: edit_quiz(course_id, quiz_id, course_material_data, response, current_user)
activate Server
Server -> Controller: search_course_by_id(course_id)
activate Controller
Controller --> Server: course
deactivate Controller
Server -> UserClass: search_teacher_by_course(course)
UserClass --> UserClass: check_authorization(current_user, teacher)
Server -> Controller: search_quiz_by_id(quiz_id)
activate Controller
Controller --> Server: quiz
deactivate Controller
Controller -> CourseMaterialQuiz: edit(name, description)
activate CourseMaterialQuiz
Controller --> Server: edited_quiz
deactivate CourseMaterialQuiz
Server --> UserActor: get_quiz(course_id, quiz_id, current_user)
deactivate Server

UserActor -> Server: delete_quiz(course_id, quiz_id, response, current_user)
activate Server
Server -> Controller: search_course_by_id(course_id)
activate Controller
Controller --> Server: course
deactivate Controller
Server -> UserClass: search_teacher_by_course(course)
UserClass --> UserClass: check_authorization(current_user, teacher)
Server -> Controller: search_quiz_by_id(quiz_id)
activate Controller
Controller --> Server: quiz
deactivate Controller
Controller -> Course: remove_quiz(quiz)
deactivate Controller
Server --> UserActor: get_learn_course_materials(course_id, current_user)
deactivate Server

UserActor -> Server: get_question(course_id, quiz_id, question_id, current_user)
activate Server
Server -> Controller: search_course_by_id(course_id)
activate Controller
Controller --> Server: course
deactivate Controller
Server -> UserClass: have_access_to_course(course)
Server -> Controller: search_quiz_by_id(quiz_id)
activate Controller
Controller --> Server: quiz
deactivate Controller
Server -> CourseMaterialQuiz: search_question_by_id(question_id)
activate CourseMaterialQuiz
CourseMaterialQuiz --> Server: question
deactivate CourseMaterialQuiz
Server --> UserActor: question_learn
deactivate Server

@enduml