@startuml

actor User
participant Controller
participant Course

User -> Controller: suggest_course()
activate Controller

Controller -> Controller: sort_course_by_rating()

loop for each course in sorted_courses
    Controller -> Course: course.get_id()
    activate Course
    Course --> Controller: course_info
    deactivate Course

    alt Course is an instance of Course
        Controller -> Course: course.get_reviews()
        activate Course
        Course --> Controller: reviews_list
        deactivate Course

        alt Course has reviews
            Controller -> CourseCardData: CourseCardData(id, name, description, price, rating, banner_image)
            activate CourseCardData
            CourseCardData --> Controller: course_card_data
            deactivate CourseCardData

            Controller --> User: course_card_data
        else Course has no reviews
            Controller --> Controller: Skip course without reviews
        end
    else Course is not an instance of Course
        Controller --> Controller: Skip invalid course
    end
end


@enduml