@startuml

actor User
participant Controller
participant Course


User -> Controller: random_course()
activate Controller

Controller -> Controller: get_all_courses()

loop for each course in all_course
    Controller -> Course: course.get_id()
    activate Course
    Course --> Controller: course_info
    deactivate Course

end

Controller -> Controller: random.sample(return_data, 3)


Controller --> User: random_course

@enduml