@startuml

actor User
participant Controller
participant Course


User -> Controller: random_reviewed_course()
activate Controller

Controller -> Controller: get_all_courses()

loop for each course in all_course
    Controller -> Course: course.get_id()
    Course --> Controller: course_info
    deactivate Course

    alt Course has reviews
        Controller -> Course: course.get_reviews()
        activate Course
        Course --> Controller: reviews_list
        deactivate Course

        alt Course has reviews
            Controller -> CourseCardData: CourseCardData(id, name, description, price, rating, banner_image)
            activate CourseCardData
            CourseCardData --> Controller: course_card_data
            deactivate CourseCardData

            Controller --> User: course_card_data
        else Course has no reviews
            Controller --> Controller: Skip course without reviews
        end
    else Course has no reviews
        Controller --> Controller: Skip course without reviews
    end
end

alt Number of reviewed courses is less than the random amount
    Controller --> User: "There is no reviewed course, yet"
else Sufficient reviewed courses available
    Controller --> User: random_reviewed_course
end

@enduml