@startuml Create Review

actor "User" as UserActor
participant "UI" as UI
participant "Controller" as Controller
participant "Course" as Course
participant "Review" as Review
participant "User" as UserClass

UserActor --> UI ++: Create Review
UI --> Controller ++: Create Review

loop Get user instance
  Controller --> UserClass ++: Get ID
  Controller <-- UserClass --: Returns ID
end

loop Get course instance
  Controller --> Course ++: Get ID
  Controller <-- Course --: return ID
end

Controller --> Course ++: Create Review
Course --> Review ++: Create Review
Course <-- Review --: Returns Review
Controller <-- Course --: Returns Course
UI <-- Controller --: Returns Course
UserActor <-- UI --: Render Course

@enduml