@startuml User
actor "User" as UserActor

participant "UI" as Server
participant Controller
participant "User" as UserClass


UserActor -> Server: View my Learning
activate Server

Server -> Controller: view_my_learning(current_user)
activate Controller
Controller -> UserClass: view_my_learning()
activate UserClass
UserClass --> Controller: my_progresses
deactivate UserClass
Controller --> Server: my_progresses
deactivate Controller

Server --> UserActor: return my learning

UserActor -> Server: view video
Server -> Controller: view_video(current_user, video_name)
activate Controller
Controller -> UserClass: view_video_by_name(video_name)
activate UserClass
UserClass --> Controller: {"video": video}
deactivate UserClass
Controller --> Server: {"video": video}
deactivate Controller

Server --> UserActor: return video

UserActor -> Server: study lastest course
Server -> Controller: study_latest_course(current_user)
activate Controller
Controller -> UserClass: get_latest_video()
activate UserClass
UserClass --> Controller: latest_video
deactivate UserClass
Controller --> Server: latest_video
deactivate Controller

Server --> UserActor: return lastest course

UserActor -> Server: search course by id from progression
Server -> Controller: search_course_by_id_from_progression(current_user, course_id)
activate Controller
Controller -> UserClass: search_course_by_id(course_id)
activate UserClass
UserClass --> Controller: course
deactivate UserClass
Controller --> Server: course
deactivate Controller

Server --> UserActor: return course id

UserActor -> Server: Get my Teacher
Server -> Controller: get_my_teaching(current_user)
activate Controller
Controller -> UserClass: get_my_teachings()
activate UserClass
UserClass --> Controller: List of courses
deactivate UserClass
Controller --> Server: List of courses
deactivate Controller

Server --> UserActor: get my teaching

UserActor -> Server: get my account info
Server -> Controller: get_my_account_info(current_user)
activate Controller
Controller -> UserClass: get_id(), get_name(), get_email()
activate UserClass
UserClass --> Controller: user info
deactivate UserClass
Controller --> Server: user info
deactivate Controller

Server --> UserActor: return account info

@enduml